version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: zolci_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: zolci_phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data: